// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/bservice.proto
 
package com.lgoo.proto;

public final class BserviceProto {
  private BserviceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BserviceEntityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string imSystem = 1;
    /**
     * <code>optional string imSystem = 1;</code>
     */
    boolean hasImSystem();
    /**
     * <code>optional string imSystem = 1;</code>
     */
    java.lang.String getImSystem();
    /**
     * <code>optional string imSystem = 1;</code>
     */
    com.google.protobuf.ByteString
        getImSystemBytes();

    // optional string toUid = 2;
    /**
     * <code>optional string toUid = 2;</code>
     */
    boolean hasToUid();
    /**
     * <code>optional string toUid = 2;</code>
     */
    java.lang.String getToUid();
    /**
     * <code>optional string toUid = 2;</code>
     */
    com.google.protobuf.ByteString
        getToUidBytes();

    // optional string ifOperator = 3;
    /**
     * <code>optional string ifOperator = 3;</code>
     */
    boolean hasIfOperator();
    /**
     * <code>optional string ifOperator = 3;</code>
     */
    java.lang.String getIfOperator();
    /**
     * <code>optional string ifOperator = 3;</code>
     */
    com.google.protobuf.ByteString
        getIfOperatorBytes();

    // optional string pageNum = 4;
    /**
     * <code>optional string pageNum = 4;</code>
     */
    boolean hasPageNum();
    /**
     * <code>optional string pageNum = 4;</code>
     */
    java.lang.String getPageNum();
    /**
     * <code>optional string pageNum = 4;</code>
     */
    com.google.protobuf.ByteString
        getPageNumBytes();

    // optional string pageSize = 5;
    /**
     * <code>optional string pageSize = 5;</code>
     */
    boolean hasPageSize();
    /**
     * <code>optional string pageSize = 5;</code>
     */
    java.lang.String getPageSize();
    /**
     * <code>optional string pageSize = 5;</code>
     */
    com.google.protobuf.ByteString
        getPageSizeBytes();
  }
  /**
   * Protobuf type {@code BserviceEntity}
   */
  public static final class BserviceEntity extends
      com.google.protobuf.GeneratedMessage
      implements BserviceEntityOrBuilder {
    // Use BserviceEntity.newBuilder() to construct.
    private BserviceEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BserviceEntity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BserviceEntity defaultInstance;
    public static BserviceEntity getDefaultInstance() {
      return defaultInstance;
    }

    public BserviceEntity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BserviceEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              imSystem_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              toUid_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              ifOperator_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              pageNum_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              pageSize_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lgoo.proto.BserviceProto.internal_static_BserviceEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lgoo.proto.BserviceProto.internal_static_BserviceEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lgoo.proto.BserviceProto.BserviceEntity.class, com.lgoo.proto.BserviceProto.BserviceEntity.Builder.class);
    }

    public static com.google.protobuf.Parser<BserviceEntity> PARSER =
        new com.google.protobuf.AbstractParser<BserviceEntity>() {
      public BserviceEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BserviceEntity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BserviceEntity> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string imSystem = 1;
    public static final int IMSYSTEM_FIELD_NUMBER = 1;
    private java.lang.Object imSystem_;
    /**
     * <code>optional string imSystem = 1;</code>
     */
    public boolean hasImSystem() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string imSystem = 1;</code>
     */
    public java.lang.String getImSystem() {
      java.lang.Object ref = imSystem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imSystem_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imSystem = 1;</code>
     */
    public com.google.protobuf.ByteString
        getImSystemBytes() {
      java.lang.Object ref = imSystem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imSystem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string toUid = 2;
    public static final int TOUID_FIELD_NUMBER = 2;
    private java.lang.Object toUid_;
    /**
     * <code>optional string toUid = 2;</code>
     */
    public boolean hasToUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string toUid = 2;</code>
     */
    public java.lang.String getToUid() {
      java.lang.Object ref = toUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toUid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string toUid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToUidBytes() {
      java.lang.Object ref = toUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ifOperator = 3;
    public static final int IFOPERATOR_FIELD_NUMBER = 3;
    private java.lang.Object ifOperator_;
    /**
     * <code>optional string ifOperator = 3;</code>
     */
    public boolean hasIfOperator() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ifOperator = 3;</code>
     */
    public java.lang.String getIfOperator() {
      java.lang.Object ref = ifOperator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ifOperator_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ifOperator = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIfOperatorBytes() {
      java.lang.Object ref = ifOperator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ifOperator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string pageNum = 4;
    public static final int PAGENUM_FIELD_NUMBER = 4;
    private java.lang.Object pageNum_;
    /**
     * <code>optional string pageNum = 4;</code>
     */
    public boolean hasPageNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string pageNum = 4;</code>
     */
    public java.lang.String getPageNum() {
      java.lang.Object ref = pageNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pageNum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pageNum = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPageNumBytes() {
      java.lang.Object ref = pageNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string pageSize = 5;
    public static final int PAGESIZE_FIELD_NUMBER = 5;
    private java.lang.Object pageSize_;
    /**
     * <code>optional string pageSize = 5;</code>
     */
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string pageSize = 5;</code>
     */
    public java.lang.String getPageSize() {
      java.lang.Object ref = pageSize_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pageSize_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pageSize = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPageSizeBytes() {
      java.lang.Object ref = pageSize_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      imSystem_ = "";
      toUid_ = "";
      ifOperator_ = "";
      pageNum_ = "";
      pageSize_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getImSystemBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getToUidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIfOperatorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPageNumBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPageSizeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getImSystemBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getToUidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIfOperatorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPageNumBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPageSizeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lgoo.proto.BserviceProto.BserviceEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.BserviceProto.BserviceEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lgoo.proto.BserviceProto.BserviceEntity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BserviceEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lgoo.proto.BserviceProto.BserviceEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lgoo.proto.BserviceProto.internal_static_BserviceEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lgoo.proto.BserviceProto.internal_static_BserviceEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lgoo.proto.BserviceProto.BserviceEntity.class, com.lgoo.proto.BserviceProto.BserviceEntity.Builder.class);
      }

      // Construct using com.lgoo.proto.BserviceProto.BserviceEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        imSystem_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        toUid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ifOperator_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pageNum_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        pageSize_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lgoo.proto.BserviceProto.internal_static_BserviceEntity_descriptor;
      }

      public com.lgoo.proto.BserviceProto.BserviceEntity getDefaultInstanceForType() {
        return com.lgoo.proto.BserviceProto.BserviceEntity.getDefaultInstance();
      }

      public com.lgoo.proto.BserviceProto.BserviceEntity build() {
        com.lgoo.proto.BserviceProto.BserviceEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lgoo.proto.BserviceProto.BserviceEntity buildPartial() {
        com.lgoo.proto.BserviceProto.BserviceEntity result = new com.lgoo.proto.BserviceProto.BserviceEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.imSystem_ = imSystem_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toUid_ = toUid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ifOperator_ = ifOperator_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pageNum_ = pageNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pageSize_ = pageSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lgoo.proto.BserviceProto.BserviceEntity) {
          return mergeFrom((com.lgoo.proto.BserviceProto.BserviceEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lgoo.proto.BserviceProto.BserviceEntity other) {
        if (other == com.lgoo.proto.BserviceProto.BserviceEntity.getDefaultInstance()) return this;
        if (other.hasImSystem()) {
          bitField0_ |= 0x00000001;
          imSystem_ = other.imSystem_;
          onChanged();
        }
        if (other.hasToUid()) {
          bitField0_ |= 0x00000002;
          toUid_ = other.toUid_;
          onChanged();
        }
        if (other.hasIfOperator()) {
          bitField0_ |= 0x00000004;
          ifOperator_ = other.ifOperator_;
          onChanged();
        }
        if (other.hasPageNum()) {
          bitField0_ |= 0x00000008;
          pageNum_ = other.pageNum_;
          onChanged();
        }
        if (other.hasPageSize()) {
          bitField0_ |= 0x00000010;
          pageSize_ = other.pageSize_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lgoo.proto.BserviceProto.BserviceEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lgoo.proto.BserviceProto.BserviceEntity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string imSystem = 1;
      private java.lang.Object imSystem_ = "";
      /**
       * <code>optional string imSystem = 1;</code>
       */
      public boolean hasImSystem() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string imSystem = 1;</code>
       */
      public java.lang.String getImSystem() {
        java.lang.Object ref = imSystem_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imSystem_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imSystem = 1;</code>
       */
      public com.google.protobuf.ByteString
          getImSystemBytes() {
        java.lang.Object ref = imSystem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imSystem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imSystem = 1;</code>
       */
      public Builder setImSystem(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        imSystem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imSystem = 1;</code>
       */
      public Builder clearImSystem() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imSystem_ = getDefaultInstance().getImSystem();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imSystem = 1;</code>
       */
      public Builder setImSystemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        imSystem_ = value;
        onChanged();
        return this;
      }

      // optional string toUid = 2;
      private java.lang.Object toUid_ = "";
      /**
       * <code>optional string toUid = 2;</code>
       */
      public boolean hasToUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string toUid = 2;</code>
       */
      public java.lang.String getToUid() {
        java.lang.Object ref = toUid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          toUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toUid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToUidBytes() {
        java.lang.Object ref = toUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toUid = 2;</code>
       */
      public Builder setToUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        toUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toUid = 2;</code>
       */
      public Builder clearToUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUid_ = getDefaultInstance().getToUid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string toUid = 2;</code>
       */
      public Builder setToUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        toUid_ = value;
        onChanged();
        return this;
      }

      // optional string ifOperator = 3;
      private java.lang.Object ifOperator_ = "";
      /**
       * <code>optional string ifOperator = 3;</code>
       */
      public boolean hasIfOperator() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ifOperator = 3;</code>
       */
      public java.lang.String getIfOperator() {
        java.lang.Object ref = ifOperator_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ifOperator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ifOperator = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIfOperatorBytes() {
        java.lang.Object ref = ifOperator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ifOperator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ifOperator = 3;</code>
       */
      public Builder setIfOperator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ifOperator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ifOperator = 3;</code>
       */
      public Builder clearIfOperator() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ifOperator_ = getDefaultInstance().getIfOperator();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ifOperator = 3;</code>
       */
      public Builder setIfOperatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ifOperator_ = value;
        onChanged();
        return this;
      }

      // optional string pageNum = 4;
      private java.lang.Object pageNum_ = "";
      /**
       * <code>optional string pageNum = 4;</code>
       */
      public boolean hasPageNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string pageNum = 4;</code>
       */
      public java.lang.String getPageNum() {
        java.lang.Object ref = pageNum_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pageNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pageNum = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPageNumBytes() {
        java.lang.Object ref = pageNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pageNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pageNum = 4;</code>
       */
      public Builder setPageNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pageNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pageNum = 4;</code>
       */
      public Builder clearPageNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pageNum_ = getDefaultInstance().getPageNum();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pageNum = 4;</code>
       */
      public Builder setPageNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pageNum_ = value;
        onChanged();
        return this;
      }

      // optional string pageSize = 5;
      private java.lang.Object pageSize_ = "";
      /**
       * <code>optional string pageSize = 5;</code>
       */
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string pageSize = 5;</code>
       */
      public java.lang.String getPageSize() {
        java.lang.Object ref = pageSize_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pageSize_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pageSize = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPageSizeBytes() {
        java.lang.Object ref = pageSize_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pageSize_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pageSize = 5;</code>
       */
      public Builder setPageSize(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pageSize = 5;</code>
       */
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pageSize_ = getDefaultInstance().getPageSize();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pageSize = 5;</code>
       */
      public Builder setPageSizeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        pageSize_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BserviceEntity)
    }

    static {
      defaultInstance = new BserviceEntity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BserviceEntity)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BserviceEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BserviceEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/bservice.proto\"h\n\016BserviceEntity" +
      "\022\020\n\010imSystem\030\001 \001(\t\022\r\n\005toUid\030\002 \001(\t\022\022\n\nifO" +
      "perator\030\003 \001(\t\022\017\n\007pageNum\030\004 \001(\t\022\020\n\010pageSi" +
      "ze\030\005 \001(\tB(\n\027com.lgoo.protoB\rBse" +
      "rviceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BserviceEntity_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BserviceEntity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BserviceEntity_descriptor,
              new java.lang.String[] { "ImSystem", "ToUid", "IfOperator", "PageNum", "PageSize", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
