// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/IM.LoginAuthentication.proto
 
package com.lgoo.proto;

public final class IMLoginAuthenticationProto {
  private IMLoginAuthenticationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code LoginCmdID}
   *
   * <pre>
   *Authentication cmd id
   * </pre>
   */
  public enum LoginCmdID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CID_Login_Authentication_Req = 12289;</code>
     *
     * <pre>
     *login authentication
     * </pre>
     */
    CID_Login_Authentication_Req(0, 12289),
    /**
     * <code>CID_Login_Authentication_Rsp = 12290;</code>
     */
    CID_Login_Authentication_Rsp(1, 12290),
    ;

    /**
     * <code>CID_Login_Authentication_Req = 12289;</code>
     *
     * <pre>
     *login authentication
     * </pre>
     */
    public static final int CID_Login_Authentication_Req_VALUE = 12289;
    /**
     * <code>CID_Login_Authentication_Rsp = 12290;</code>
     */
    public static final int CID_Login_Authentication_Rsp_VALUE = 12290;


    public final int getNumber() { return value; }

    public static LoginCmdID valueOf(int value) {
      switch (value) {
        case 12289: return CID_Login_Authentication_Req;
        case 12290: return CID_Login_Authentication_Rsp;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoginCmdID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LoginCmdID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoginCmdID>() {
            public LoginCmdID findValueByNumber(int number) {
              return LoginCmdID.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lgoo.proto.IMLoginAuthenticationProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final LoginCmdID[] VALUES = values();

    public static LoginCmdID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LoginCmdID(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LoginCmdID)
  }

  /**
   * Protobuf enum {@code CustType}
   */
  public enum CustType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CUST_TYPE_2 = 2;</code>
     *
     * <pre>
     *成员企业
     * </pre>
     */
    CUST_TYPE_2(0, 2),
    /**
     * <code>CUST_TYPE_3 = 3;</code>
     *
     * <pre>
     *托管企业
     * </pre>
     */
    CUST_TYPE_3(1, 3),
    /**
     * <code>CUST_TYPE_4 = 4;</code>
     *
     * <pre>
     *服务公司
     * </pre>
     */
    CUST_TYPE_4(2, 4),
    /**
     * <code>CUST_TYPE_5 = 5;</code>
     *
     * <pre>
     *管理公司
     * </pre>
     */
    CUST_TYPE_5(3, 5),
    /**
     * <code>CUST_TYPE_6 = 6;</code>
     *
     * <pre>
     *地区平台
     * </pre>
     */
    CUST_TYPE_6(4, 6),
    ;

    /**
     * <code>CUST_TYPE_2 = 2;</code>
     *
     * <pre>
     *成员企业
     * </pre>
     */
    public static final int CUST_TYPE_2_VALUE = 2;
    /**
     * <code>CUST_TYPE_3 = 3;</code>
     *
     * <pre>
     *托管企业
     * </pre>
     */
    public static final int CUST_TYPE_3_VALUE = 3;
    /**
     * <code>CUST_TYPE_4 = 4;</code>
     *
     * <pre>
     *服务公司
     * </pre>
     */
    public static final int CUST_TYPE_4_VALUE = 4;
    /**
     * <code>CUST_TYPE_5 = 5;</code>
     *
     * <pre>
     *管理公司
     * </pre>
     */
    public static final int CUST_TYPE_5_VALUE = 5;
    /**
     * <code>CUST_TYPE_6 = 6;</code>
     *
     * <pre>
     *地区平台
     * </pre>
     */
    public static final int CUST_TYPE_6_VALUE = 6;


    public final int getNumber() { return value; }

    public static CustType valueOf(int value) {
      switch (value) {
        case 2: return CUST_TYPE_2;
        case 3: return CUST_TYPE_3;
        case 4: return CUST_TYPE_4;
        case 5: return CUST_TYPE_5;
        case 6: return CUST_TYPE_6;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CustType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CustType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CustType>() {
            public CustType findValueByNumber(int number) {
              return CustType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lgoo.proto.IMLoginAuthenticationProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final CustType[] VALUES = values();

    public static CustType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CustType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CustType)
  }

  public interface MessageLoginAuthticationReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string resNo = 1;
    /**
     * <code>required string resNo = 1;</code>
     *
     * <pre>
     *互生号
     * </pre>
     */
    boolean hasResNo();
    /**
     * <code>required string resNo = 1;</code>
     *
     * <pre>
     *互生号
     * </pre>
     */
    java.lang.String getResNo();
    /**
     * <code>required string resNo = 1;</code>
     *
     * <pre>
     *互生号
     * </pre>
     */
    com.google.protobuf.ByteString
        getResNoBytes();

    // required string userName = 2;
    /**
     * <code>required string userName = 2;</code>
     *
     * <pre>
     *操作员账号
     * </pre>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 2;</code>
     *
     * <pre>
     *操作员账号
     * </pre>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 2;</code>
     *
     * <pre>
     *操作员账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required string loginPwd = 3;
    /**
     * <code>required string loginPwd = 3;</code>
     *
     * <pre>
     *登陆密码
     * </pre>
     */
    boolean hasLoginPwd();
    /**
     * <code>required string loginPwd = 3;</code>
     *
     * <pre>
     *登陆密码
     * </pre>
     */
    java.lang.String getLoginPwd();
    /**
     * <code>required string loginPwd = 3;</code>
     *
     * <pre>
     *登陆密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getLoginPwdBytes();

    // optional string pwdVer = 4;
    /**
     * <code>optional string pwdVer = 4;</code>
     *
     * <pre>
     *密码版本号
     * </pre>
     */
    boolean hasPwdVer();
    /**
     * <code>optional string pwdVer = 4;</code>
     *
     * <pre>
     *密码版本号
     * </pre>
     */
    java.lang.String getPwdVer();
    /**
     * <code>optional string pwdVer = 4;</code>
     *
     * <pre>
     *密码版本号
     * </pre>
     */
    com.google.protobuf.ByteString
        getPwdVerBytes();

    // required string randomToken = 5;
    /**
     * <code>required string randomToken = 5;</code>
     *
     * <pre>
     *随机token
     * </pre>
     */
    boolean hasRandomToken();
    /**
     * <code>required string randomToken = 5;</code>
     *
     * <pre>
     *随机token
     * </pre>
     */
    java.lang.String getRandomToken();
    /**
     * <code>required string randomToken = 5;</code>
     *
     * <pre>
     *随机token
     * </pre>
     */
    com.google.protobuf.ByteString
        getRandomTokenBytes();

    // optional string loginIp = 6;
    /**
     * <code>optional string loginIp = 6;</code>
     *
     * <pre>
     *登录IP
     * </pre>
     */
    boolean hasLoginIp();
    /**
     * <code>optional string loginIp = 6;</code>
     *
     * <pre>
     *登录IP
     * </pre>
     */
    java.lang.String getLoginIp();
    /**
     * <code>optional string loginIp = 6;</code>
     *
     * <pre>
     *登录IP
     * </pre>
     */
    com.google.protobuf.ByteString
        getLoginIpBytes();

    // required .CustType custType = 7;
    /**
     * <code>required .CustType custType = 7;</code>
     *
     * <pre>
     *客户类型
     * </pre>
     */
    boolean hasCustType();
    /**
     * <code>required .CustType custType = 7;</code>
     *
     * <pre>
     *客户类型
     * </pre>
     */
    com.lgoo.proto.IMLoginAuthenticationProto.CustType getCustType();
  }
  /**
   * Protobuf type {@code MessageLoginAuthticationReq}
   */
  public static final class MessageLoginAuthticationReq extends
      com.google.protobuf.GeneratedMessage
      implements MessageLoginAuthticationReqOrBuilder {
    // Use MessageLoginAuthticationReq.newBuilder() to construct.
    private MessageLoginAuthticationReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageLoginAuthticationReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageLoginAuthticationReq defaultInstance;
    public static MessageLoginAuthticationReq getDefaultInstance() {
      return defaultInstance;
    }

    public MessageLoginAuthticationReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageLoginAuthticationReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              resNo_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              loginPwd_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              pwdVer_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              randomToken_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              loginIp_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.lgoo.proto.IMLoginAuthenticationProto.CustType value = com.lgoo.proto.IMLoginAuthenticationProto.CustType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                custType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq.class, com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageLoginAuthticationReq> PARSER =
        new com.google.protobuf.AbstractParser<MessageLoginAuthticationReq>() {
      public MessageLoginAuthticationReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageLoginAuthticationReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageLoginAuthticationReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string resNo = 1;
    public static final int RESNO_FIELD_NUMBER = 1;
    private java.lang.Object resNo_;
    /**
     * <code>required string resNo = 1;</code>
     *
     * <pre>
     *互生号
     * </pre>
     */
    public boolean hasResNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string resNo = 1;</code>
     *
     * <pre>
     *互生号
     * </pre>
     */
    public java.lang.String getResNo() {
      java.lang.Object ref = resNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string resNo = 1;</code>
     *
     * <pre>
     *互生号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResNoBytes() {
      java.lang.Object ref = resNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string userName = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 2;</code>
     *
     * <pre>
     *操作员账号
     * </pre>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userName = 2;</code>
     *
     * <pre>
     *操作员账号
     * </pre>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 2;</code>
     *
     * <pre>
     *操作员账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string loginPwd = 3;
    public static final int LOGINPWD_FIELD_NUMBER = 3;
    private java.lang.Object loginPwd_;
    /**
     * <code>required string loginPwd = 3;</code>
     *
     * <pre>
     *登陆密码
     * </pre>
     */
    public boolean hasLoginPwd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string loginPwd = 3;</code>
     *
     * <pre>
     *登陆密码
     * </pre>
     */
    public java.lang.String getLoginPwd() {
      java.lang.Object ref = loginPwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginPwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string loginPwd = 3;</code>
     *
     * <pre>
     *登陆密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLoginPwdBytes() {
      java.lang.Object ref = loginPwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string pwdVer = 4;
    public static final int PWDVER_FIELD_NUMBER = 4;
    private java.lang.Object pwdVer_;
    /**
     * <code>optional string pwdVer = 4;</code>
     *
     * <pre>
     *密码版本号
     * </pre>
     */
    public boolean hasPwdVer() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string pwdVer = 4;</code>
     *
     * <pre>
     *密码版本号
     * </pre>
     */
    public java.lang.String getPwdVer() {
      java.lang.Object ref = pwdVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pwdVer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pwdVer = 4;</code>
     *
     * <pre>
     *密码版本号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPwdVerBytes() {
      java.lang.Object ref = pwdVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pwdVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string randomToken = 5;
    public static final int RANDOMTOKEN_FIELD_NUMBER = 5;
    private java.lang.Object randomToken_;
    /**
     * <code>required string randomToken = 5;</code>
     *
     * <pre>
     *随机token
     * </pre>
     */
    public boolean hasRandomToken() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string randomToken = 5;</code>
     *
     * <pre>
     *随机token
     * </pre>
     */
    public java.lang.String getRandomToken() {
      java.lang.Object ref = randomToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          randomToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string randomToken = 5;</code>
     *
     * <pre>
     *随机token
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRandomTokenBytes() {
      java.lang.Object ref = randomToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        randomToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string loginIp = 6;
    public static final int LOGINIP_FIELD_NUMBER = 6;
    private java.lang.Object loginIp_;
    /**
     * <code>optional string loginIp = 6;</code>
     *
     * <pre>
     *登录IP
     * </pre>
     */
    public boolean hasLoginIp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string loginIp = 6;</code>
     *
     * <pre>
     *登录IP
     * </pre>
     */
    public java.lang.String getLoginIp() {
      java.lang.Object ref = loginIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string loginIp = 6;</code>
     *
     * <pre>
     *登录IP
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLoginIpBytes() {
      java.lang.Object ref = loginIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .CustType custType = 7;
    public static final int CUSTTYPE_FIELD_NUMBER = 7;
    private com.lgoo.proto.IMLoginAuthenticationProto.CustType custType_;
    /**
     * <code>required .CustType custType = 7;</code>
     *
     * <pre>
     *客户类型
     * </pre>
     */
    public boolean hasCustType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required .CustType custType = 7;</code>
     *
     * <pre>
     *客户类型
     * </pre>
     */
    public com.lgoo.proto.IMLoginAuthenticationProto.CustType getCustType() {
      return custType_;
    }

    private void initFields() {
      resNo_ = "";
      userName_ = "";
      loginPwd_ = "";
      pwdVer_ = "";
      randomToken_ = "";
      loginIp_ = "";
      custType_ = com.lgoo.proto.IMLoginAuthenticationProto.CustType.CUST_TYPE_2;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoginPwd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRandomToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCustType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResNoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLoginPwdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPwdVerBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getRandomTokenBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getLoginIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, custType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResNoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLoginPwdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPwdVerBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getRandomTokenBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getLoginIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, custType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageLoginAuthticationReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq.class, com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq.Builder.class);
      }

      // Construct using com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        loginPwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pwdVer_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        randomToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        loginIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        custType_ = com.lgoo.proto.IMLoginAuthenticationProto.CustType.CUST_TYPE_2;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationReq_descriptor;
      }

      public com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq getDefaultInstanceForType() {
        return com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq.getDefaultInstance();
      }

      public com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq build() {
        com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq buildPartial() {
        com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq result = new com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resNo_ = resNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.loginPwd_ = loginPwd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pwdVer_ = pwdVer_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.randomToken_ = randomToken_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.loginIp_ = loginIp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.custType_ = custType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq) {
          return mergeFrom((com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq other) {
        if (other == com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq.getDefaultInstance()) return this;
        if (other.hasResNo()) {
          bitField0_ |= 0x00000001;
          resNo_ = other.resNo_;
          onChanged();
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasLoginPwd()) {
          bitField0_ |= 0x00000004;
          loginPwd_ = other.loginPwd_;
          onChanged();
        }
        if (other.hasPwdVer()) {
          bitField0_ |= 0x00000008;
          pwdVer_ = other.pwdVer_;
          onChanged();
        }
        if (other.hasRandomToken()) {
          bitField0_ |= 0x00000010;
          randomToken_ = other.randomToken_;
          onChanged();
        }
        if (other.hasLoginIp()) {
          bitField0_ |= 0x00000020;
          loginIp_ = other.loginIp_;
          onChanged();
        }
        if (other.hasCustType()) {
          setCustType(other.getCustType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResNo()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasLoginPwd()) {
          
          return false;
        }
        if (!hasRandomToken()) {
          
          return false;
        }
        if (!hasCustType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string resNo = 1;
      private java.lang.Object resNo_ = "";
      /**
       * <code>required string resNo = 1;</code>
       *
       * <pre>
       *互生号
       * </pre>
       */
      public boolean hasResNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string resNo = 1;</code>
       *
       * <pre>
       *互生号
       * </pre>
       */
      public java.lang.String getResNo() {
        java.lang.Object ref = resNo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string resNo = 1;</code>
       *
       * <pre>
       *互生号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResNoBytes() {
        java.lang.Object ref = resNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string resNo = 1;</code>
       *
       * <pre>
       *互生号
       * </pre>
       */
      public Builder setResNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string resNo = 1;</code>
       *
       * <pre>
       *互生号
       * </pre>
       */
      public Builder clearResNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resNo_ = getDefaultInstance().getResNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string resNo = 1;</code>
       *
       * <pre>
       *互生号
       * </pre>
       */
      public Builder setResNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resNo_ = value;
        onChanged();
        return this;
      }

      // required string userName = 2;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 2;</code>
       *
       * <pre>
       *操作员账号
       * </pre>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userName = 2;</code>
       *
       * <pre>
       *操作员账号
       * </pre>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       *
       * <pre>
       *操作员账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       *
       * <pre>
       *操作员账号
       * </pre>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       *
       * <pre>
       *操作员账号
       * </pre>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       *
       * <pre>
       *操作员账号
       * </pre>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      // required string loginPwd = 3;
      private java.lang.Object loginPwd_ = "";
      /**
       * <code>required string loginPwd = 3;</code>
       *
       * <pre>
       *登陆密码
       * </pre>
       */
      public boolean hasLoginPwd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string loginPwd = 3;</code>
       *
       * <pre>
       *登陆密码
       * </pre>
       */
      public java.lang.String getLoginPwd() {
        java.lang.Object ref = loginPwd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          loginPwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string loginPwd = 3;</code>
       *
       * <pre>
       *登陆密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLoginPwdBytes() {
        java.lang.Object ref = loginPwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginPwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string loginPwd = 3;</code>
       *
       * <pre>
       *登陆密码
       * </pre>
       */
      public Builder setLoginPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        loginPwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string loginPwd = 3;</code>
       *
       * <pre>
       *登陆密码
       * </pre>
       */
      public Builder clearLoginPwd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        loginPwd_ = getDefaultInstance().getLoginPwd();
        onChanged();
        return this;
      }
      /**
       * <code>required string loginPwd = 3;</code>
       *
       * <pre>
       *登陆密码
       * </pre>
       */
      public Builder setLoginPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        loginPwd_ = value;
        onChanged();
        return this;
      }

      // optional string pwdVer = 4;
      private java.lang.Object pwdVer_ = "";
      /**
       * <code>optional string pwdVer = 4;</code>
       *
       * <pre>
       *密码版本号
       * </pre>
       */
      public boolean hasPwdVer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string pwdVer = 4;</code>
       *
       * <pre>
       *密码版本号
       * </pre>
       */
      public java.lang.String getPwdVer() {
        java.lang.Object ref = pwdVer_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pwdVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pwdVer = 4;</code>
       *
       * <pre>
       *密码版本号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPwdVerBytes() {
        java.lang.Object ref = pwdVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pwdVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pwdVer = 4;</code>
       *
       * <pre>
       *密码版本号
       * </pre>
       */
      public Builder setPwdVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pwdVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwdVer = 4;</code>
       *
       * <pre>
       *密码版本号
       * </pre>
       */
      public Builder clearPwdVer() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pwdVer_ = getDefaultInstance().getPwdVer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwdVer = 4;</code>
       *
       * <pre>
       *密码版本号
       * </pre>
       */
      public Builder setPwdVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pwdVer_ = value;
        onChanged();
        return this;
      }

      // required string randomToken = 5;
      private java.lang.Object randomToken_ = "";
      /**
       * <code>required string randomToken = 5;</code>
       *
       * <pre>
       *随机token
       * </pre>
       */
      public boolean hasRandomToken() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string randomToken = 5;</code>
       *
       * <pre>
       *随机token
       * </pre>
       */
      public java.lang.String getRandomToken() {
        java.lang.Object ref = randomToken_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          randomToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string randomToken = 5;</code>
       *
       * <pre>
       *随机token
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRandomTokenBytes() {
        java.lang.Object ref = randomToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          randomToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string randomToken = 5;</code>
       *
       * <pre>
       *随机token
       * </pre>
       */
      public Builder setRandomToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        randomToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string randomToken = 5;</code>
       *
       * <pre>
       *随机token
       * </pre>
       */
      public Builder clearRandomToken() {
        bitField0_ = (bitField0_ & ~0x00000010);
        randomToken_ = getDefaultInstance().getRandomToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string randomToken = 5;</code>
       *
       * <pre>
       *随机token
       * </pre>
       */
      public Builder setRandomTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        randomToken_ = value;
        onChanged();
        return this;
      }

      // optional string loginIp = 6;
      private java.lang.Object loginIp_ = "";
      /**
       * <code>optional string loginIp = 6;</code>
       *
       * <pre>
       *登录IP
       * </pre>
       */
      public boolean hasLoginIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string loginIp = 6;</code>
       *
       * <pre>
       *登录IP
       * </pre>
       */
      public java.lang.String getLoginIp() {
        java.lang.Object ref = loginIp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          loginIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string loginIp = 6;</code>
       *
       * <pre>
       *登录IP
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLoginIpBytes() {
        java.lang.Object ref = loginIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string loginIp = 6;</code>
       *
       * <pre>
       *登录IP
       * </pre>
       */
      public Builder setLoginIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        loginIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string loginIp = 6;</code>
       *
       * <pre>
       *登录IP
       * </pre>
       */
      public Builder clearLoginIp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        loginIp_ = getDefaultInstance().getLoginIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string loginIp = 6;</code>
       *
       * <pre>
       *登录IP
       * </pre>
       */
      public Builder setLoginIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        loginIp_ = value;
        onChanged();
        return this;
      }

      // required .CustType custType = 7;
      private com.lgoo.proto.IMLoginAuthenticationProto.CustType custType_ = com.lgoo.proto.IMLoginAuthenticationProto.CustType.CUST_TYPE_2;
      /**
       * <code>required .CustType custType = 7;</code>
       *
       * <pre>
       *客户类型
       * </pre>
       */
      public boolean hasCustType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required .CustType custType = 7;</code>
       *
       * <pre>
       *客户类型
       * </pre>
       */
      public com.lgoo.proto.IMLoginAuthenticationProto.CustType getCustType() {
        return custType_;
      }
      /**
       * <code>required .CustType custType = 7;</code>
       *
       * <pre>
       *客户类型
       * </pre>
       */
      public Builder setCustType(com.lgoo.proto.IMLoginAuthenticationProto.CustType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        custType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .CustType custType = 7;</code>
       *
       * <pre>
       *客户类型
       * </pre>
       */
      public Builder clearCustType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        custType_ = com.lgoo.proto.IMLoginAuthenticationProto.CustType.CUST_TYPE_2;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MessageLoginAuthticationReq)
    }

    static {
      defaultInstance = new MessageLoginAuthticationReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MessageLoginAuthticationReq)
  }

  public interface MessageLoginAuthticationRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string result_json = 1;
    /**
     * <code>required string result_json = 1;</code>
     *
     * <pre>
     *验证结果
     * </pre>
     */
    boolean hasResultJson();
    /**
     * <code>required string result_json = 1;</code>
     *
     * <pre>
     *验证结果
     * </pre>
     */
    java.lang.String getResultJson();
    /**
     * <code>required string result_json = 1;</code>
     *
     * <pre>
     *验证结果
     * </pre>
     */
    com.google.protobuf.ByteString
        getResultJsonBytes();
  }
  /**
   * Protobuf type {@code MessageLoginAuthticationRsp}
   */
  public static final class MessageLoginAuthticationRsp extends
      com.google.protobuf.GeneratedMessage
      implements MessageLoginAuthticationRspOrBuilder {
    // Use MessageLoginAuthticationRsp.newBuilder() to construct.
    private MessageLoginAuthticationRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageLoginAuthticationRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageLoginAuthticationRsp defaultInstance;
    public static MessageLoginAuthticationRsp getDefaultInstance() {
      return defaultInstance;
    }

    public MessageLoginAuthticationRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageLoginAuthticationRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              resultJson_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp.class, com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageLoginAuthticationRsp> PARSER =
        new com.google.protobuf.AbstractParser<MessageLoginAuthticationRsp>() {
      public MessageLoginAuthticationRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageLoginAuthticationRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageLoginAuthticationRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string result_json = 1;
    public static final int RESULT_JSON_FIELD_NUMBER = 1;
    private java.lang.Object resultJson_;
    /**
     * <code>required string result_json = 1;</code>
     *
     * <pre>
     *验证结果
     * </pre>
     */
    public boolean hasResultJson() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string result_json = 1;</code>
     *
     * <pre>
     *验证结果
     * </pre>
     */
    public java.lang.String getResultJson() {
      java.lang.Object ref = resultJson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultJson_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result_json = 1;</code>
     *
     * <pre>
     *验证结果
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResultJsonBytes() {
      java.lang.Object ref = resultJson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resultJson_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultJson()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultJsonBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultJsonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageLoginAuthticationRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp.class, com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp.Builder.class);
      }

      // Construct using com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultJson_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lgoo.proto.IMLoginAuthenticationProto.internal_static_MessageLoginAuthticationRsp_descriptor;
      }

      public com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp getDefaultInstanceForType() {
        return com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp.getDefaultInstance();
      }

      public com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp build() {
        com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp buildPartial() {
        com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp result = new com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultJson_ = resultJson_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp) {
          return mergeFrom((com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp other) {
        if (other == com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp.getDefaultInstance()) return this;
        if (other.hasResultJson()) {
          bitField0_ |= 0x00000001;
          resultJson_ = other.resultJson_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultJson()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lgoo.proto.IMLoginAuthenticationProto.MessageLoginAuthticationRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string result_json = 1;
      private java.lang.Object resultJson_ = "";
      /**
       * <code>required string result_json = 1;</code>
       *
       * <pre>
       *验证结果
       * </pre>
       */
      public boolean hasResultJson() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string result_json = 1;</code>
       *
       * <pre>
       *验证结果
       * </pre>
       */
      public java.lang.String getResultJson() {
        java.lang.Object ref = resultJson_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resultJson_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string result_json = 1;</code>
       *
       * <pre>
       *验证结果
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResultJsonBytes() {
        java.lang.Object ref = resultJson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultJson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result_json = 1;</code>
       *
       * <pre>
       *验证结果
       * </pre>
       */
      public Builder setResultJson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultJson_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string result_json = 1;</code>
       *
       * <pre>
       *验证结果
       * </pre>
       */
      public Builder clearResultJson() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultJson_ = getDefaultInstance().getResultJson();
        onChanged();
        return this;
      }
      /**
       * <code>required string result_json = 1;</code>
       *
       * <pre>
       *验证结果
       * </pre>
       */
      public Builder setResultJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultJson_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MessageLoginAuthticationRsp)
    }

    static {
      defaultInstance = new MessageLoginAuthticationRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MessageLoginAuthticationRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageLoginAuthticationReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageLoginAuthticationReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageLoginAuthticationRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageLoginAuthticationRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"proto/IM.LoginAuthentication.proto\"\243\001\n" +
      "\033MessageLoginAuthticationReq\022\r\n\005resNo\030\001 " +
      "\002(\t\022\020\n\010userName\030\002 \002(\t\022\020\n\010loginPwd\030\003 \002(\t\022" +
      "\016\n\006pwdVer\030\004 \001(\t\022\023\n\013randomToken\030\005 \002(\t\022\017\n\007" +
      "loginIp\030\006 \001(\t\022\033\n\010custType\030\007 \002(\0162\t.CustTy" +
      "pe\"2\n\033MessageLoginAuthticationRsp\022\023\n\013res" +
      "ult_json\030\001 \002(\t*R\n\nLoginCmdID\022!\n\034CID_Logi" +
      "n_Authentication_Req\020\201`\022!\n\034CID_Login_Aut" +
      "hentication_Rsp\020\202`*_\n\010CustType\022\017\n\013CUST_T" +
      "YPE_2\020\002\022\017\n\013CUST_TYPE_3\020\003\022\017\n\013CUST_TYPE_4\020",
      "\004\022\017\n\013CUST_TYPE_5\020\005\022\017\n\013CUST_TYPE_6\020\006B5\n\027c" +
      "om.gy.hsim.netty.protoB\032IMLoginAuthentic" +
      "ationProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MessageLoginAuthticationReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MessageLoginAuthticationReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageLoginAuthticationReq_descriptor,
              new java.lang.String[] { "ResNo", "UserName", "LoginPwd", "PwdVer", "RandomToken", "LoginIp", "CustType", });
          internal_static_MessageLoginAuthticationRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MessageLoginAuthticationRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageLoginAuthticationRsp_descriptor,
              new java.lang.String[] { "ResultJson", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
