// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Apns.proto

package com.lgoo.proto.IM.Apns;

public final class IMApns {
  private IMApns() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ApnsPushReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Apns.ApnsPushReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated string tokenlist = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getTokenlistList();
    /**
     * <code>repeated string tokenlist = 1;</code>
     */
    int getTokenlistCount();
    /**
     * <code>repeated string tokenlist = 1;</code>
     */
    java.lang.String getTokenlist(int index);
    /**
     * <code>repeated string tokenlist = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenlistBytes(int index);
  }
  /**
   * Protobuf type {@code IM.Apns.ApnsPushReq}
   */
  public static final class ApnsPushReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Apns.ApnsPushReq)
      ApnsPushReqOrBuilder {
    // Use ApnsPushReq.newBuilder() to construct.
    private ApnsPushReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ApnsPushReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final ApnsPushReq defaultInstance;
    public static ApnsPushReq getDefaultInstance() {
      return defaultInstance;
    }

    public ApnsPushReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private ApnsPushReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                tokenlist_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              tokenlist_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          tokenlist_ = tokenlist_.getUnmodifiableView();
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ApnsPushReq> PARSER =
        new com.google.protobuf.AbstractParser<ApnsPushReq>() {
      public ApnsPushReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApnsPushReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ApnsPushReq> getParserForType() {
      return PARSER;
    }

    public static final int TOKENLIST_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList tokenlist_;
    /**
     * <code>repeated string tokenlist = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTokenlistList() {
      return tokenlist_;
    }
    /**
     * <code>repeated string tokenlist = 1;</code>
     */
    public int getTokenlistCount() {
      return tokenlist_.size();
    }
    /**
     * <code>repeated string tokenlist = 1;</code>
     */
    public java.lang.String getTokenlist(int index) {
      return tokenlist_.get(index);
    }
    /**
     * <code>repeated string tokenlist = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenlistBytes(int index) {
      return tokenlist_.getByteString(index);
    }

    private void initFields() {
      tokenlist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < tokenlist_.size(); i++) {
        output.writeBytes(1, tokenlist_.getByteString(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < tokenlist_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(tokenlist_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTokenlistList().size();
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Apns.ApnsPushReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Apns.ApnsPushReq)
        com.lgoo.proto.IM.Apns.IMApns.ApnsPushReqOrBuilder {
      // Construct using IM.Apns.IMApns.ApnsPushReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tokenlist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq getDefaultInstanceForType() {
        return com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq.getDefaultInstance();
      }

      public com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq build() {
        com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq buildPartial() {
        com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq result = new com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          tokenlist_ = tokenlist_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tokenlist_ = tokenlist_;
        return result;
      }

      public Builder mergeFrom(com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq other) {
        if (other == com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq.getDefaultInstance()) return this;
        if (!other.tokenlist_.isEmpty()) {
          if (tokenlist_.isEmpty()) {
            tokenlist_ = other.tokenlist_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTokenlistIsMutable();
            tokenlist_.addAll(other.tokenlist_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lgoo.proto.IM.Apns.IMApns.ApnsPushReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList tokenlist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTokenlistIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          tokenlist_ = new com.google.protobuf.LazyStringArrayList(tokenlist_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTokenlistList() {
        return tokenlist_.getUnmodifiableView();
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public int getTokenlistCount() {
        return tokenlist_.size();
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public java.lang.String getTokenlist(int index) {
        return tokenlist_.get(index);
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenlistBytes(int index) {
        return tokenlist_.getByteString(index);
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public Builder setTokenlist(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTokenlistIsMutable();
        tokenlist_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public Builder addTokenlist(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTokenlistIsMutable();
        tokenlist_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public Builder addAllTokenlist(
          java.lang.Iterable<java.lang.String> values) {
        ensureTokenlistIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tokenlist_);
        
        return this;
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public Builder clearTokenlist() {
        tokenlist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      /**
       * <code>repeated string tokenlist = 1;</code>
       */
      public Builder addTokenlistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTokenlistIsMutable();
        tokenlist_.add(value);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Apns.ApnsPushReq)
    }

    static {
      defaultInstance = new ApnsPushReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Apns.ApnsPushReq)
  }

  public interface ApnsPushRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Apns.ApnsPushRsp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 ret = 1;</code>
     */
    boolean hasRet();
    /**
     * <code>optional uint32 ret = 1;</code>
     */
    int getRet();

    /**
     * <code>optional bytes strinfo = 2;</code>
     */
    boolean hasStrinfo();
    /**
     * <code>optional bytes strinfo = 2;</code>
     */
    com.google.protobuf.ByteString getStrinfo();
  }
  /**
   * Protobuf type {@code IM.Apns.ApnsPushRsp}
   */
  public static final class ApnsPushRsp extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Apns.ApnsPushRsp)
      ApnsPushRspOrBuilder {
    // Use ApnsPushRsp.newBuilder() to construct.
    private ApnsPushRsp(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ApnsPushRsp(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final ApnsPushRsp defaultInstance;
    public static ApnsPushRsp getDefaultInstance() {
      return defaultInstance;
    }

    public ApnsPushRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private ApnsPushRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              strinfo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ApnsPushRsp> PARSER =
        new com.google.protobuf.AbstractParser<ApnsPushRsp>() {
      public ApnsPushRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApnsPushRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ApnsPushRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>optional uint32 ret = 1;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }

    public static final int STRINFO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString strinfo_;
    /**
     * <code>optional bytes strinfo = 2;</code>
     */
    public boolean hasStrinfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes strinfo = 2;</code>
     */
    public com.google.protobuf.ByteString getStrinfo() {
      return strinfo_;
    }

    private void initFields() {
      ret_ = 0;
      strinfo_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, strinfo_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, ret_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, strinfo_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Apns.ApnsPushRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Apns.ApnsPushRsp)
        com.lgoo.proto.IM.Apns.IMApns.ApnsPushRspOrBuilder {
      // Construct using IM.Apns.IMApns.ApnsPushRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        strinfo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp getDefaultInstanceForType() {
        return com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp.getDefaultInstance();
      }

      public com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp build() {
        com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp buildPartial() {
        com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp result = new com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.strinfo_ = strinfo_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp other) {
        if (other == com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasStrinfo()) {
          setStrinfo(other.getStrinfo());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lgoo.proto.IM.Apns.IMApns.ApnsPushRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ret_ ;
      /**
       * <code>optional uint32 ret = 1;</code>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 ret = 1;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>optional uint32 ret = 1;</code>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        
        return this;
      }
      /**
       * <code>optional uint32 ret = 1;</code>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        
        return this;
      }

      private com.google.protobuf.ByteString strinfo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes strinfo = 2;</code>
       */
      public boolean hasStrinfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes strinfo = 2;</code>
       */
      public com.google.protobuf.ByteString getStrinfo() {
        return strinfo_;
      }
      /**
       * <code>optional bytes strinfo = 2;</code>
       */
      public Builder setStrinfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        strinfo_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes strinfo = 2;</code>
       */
      public Builder clearStrinfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        strinfo_ = getDefaultInstance().getStrinfo();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Apns.ApnsPushRsp)
    }

    static {
      defaultInstance = new ApnsPushRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Apns.ApnsPushRsp)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
